#include <dark/darkstar.h>

int main()
{
    const Dark_Growth g1 = { 0.0f, 10, 0 };
    DARK_TEST_EQ_U(DARK_GROWTH_VALUE(0, g1), 10);

    const Dark_Growth g2 = { 2.0f, 0, 4};
    DARK_TEST_EQ_U(DARK_GROWTH_VALUE(8, g2), 4);

    const Dark_Growth g3 = { 2.0f, 20, 20};
    DARK_TEST_EQ_U(DARK_GROWTH_VALUE(8, g3), 20);

    const Dark_Growth g4 = { 2.0f, 0, 0};
    DARK_TEST_EQ_U(DARK_GROWTH_VALUE(8, g4), 16);

    DARK_TEST_EQ_U(DARK_GROWTH_VALUE(0, DARK_GROWTH_STANDARD), 1);
    DARK_TEST_EQ_U(DARK_GROWTH_VALUE(1, DARK_GROWTH_STANDARD), 1);
    DARK_TEST_EQ_U(DARK_GROWTH_VALUE(2, DARK_GROWTH_STANDARD), 1);
    DARK_TEST_EQ_U(DARK_GROWTH_VALUE(3, DARK_GROWTH_STANDARD), 1);
    DARK_TEST_EQ_U(DARK_GROWTH_VALUE(4, DARK_GROWTH_STANDARD), 2);
    DARK_TEST_EQ_U(DARK_GROWTH_VALUE(5, DARK_GROWTH_STANDARD), 2);
    DARK_TEST_EQ_U(DARK_GROWTH_VALUE(6, DARK_GROWTH_STANDARD), 3);
    DARK_TEST_EQ_U(DARK_GROWTH_VALUE(100, DARK_GROWTH_STANDARD), 50);

    DARK_TEST_EQ_U(DARK_GROWTH_APPLIED(0, DARK_GROWTH_STANDARD), 1);
    DARK_TEST_EQ_U(DARK_GROWTH_APPLIED(1, DARK_GROWTH_STANDARD), 2);
    DARK_TEST_EQ_U(DARK_GROWTH_APPLIED(2, DARK_GROWTH_STANDARD), 3);
    DARK_TEST_EQ_U(DARK_GROWTH_APPLIED(3, DARK_GROWTH_STANDARD), 4);
    DARK_TEST_EQ_U(DARK_GROWTH_APPLIED(4, DARK_GROWTH_STANDARD), 6);
    DARK_TEST_EQ_U(DARK_GROWTH_APPLIED(5, DARK_GROWTH_STANDARD), 7);
    DARK_TEST_EQ_U(DARK_GROWTH_APPLIED(6, DARK_GROWTH_STANDARD), 9);
    DARK_TEST_EQ_U(DARK_GROWTH_APPLIED(100, DARK_GROWTH_STANDARD), 150);

    return EXIT_SUCCESS;
}
